name: build with gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v2
        with:
          arguments: build
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
